# Generated by Django 2.0.3 on 2018-08-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField()),
                ('order_number', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(null=True)),
                ('cancelled_at', models.DateTimeField(null=True)),
                ('tnt_number', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
